### ISSUE TITLE
PAN08-support?

### ISSUE THREAD

**Issue by cbho** [JohanBendz/com.philio#25]
Asked at the app store, but not sure if it's read:
What are the perspectives on adding support for the PAN08-roller shutter?
Regards,
Chr.

**Comment by Inversion-NL** [comment]
Since I don't have the device I'm not implementing it, sorry.
GitHub pull requests are more than welcome though!

**Comment by Drops70** [comment]
I am also interested in the support for the PAN08 roller shutter as I hava already seven of These installed in my home.
If a device is needed I can send you one for implementation.

**Comment by Drops70** [comment]
Or you might only need the three IDs ?
Man-ID: 316 
Product Type ID: 1 
Product ID: 6

**Comment by Inversion-NL** [comment]
Please create an pull request. I'll be more than happy to merge it.
I don't have much time, sorry

**Comment by Drops70** [comment]
Thanks for Feedback. Opened a pull request. Hope I did it right as I am totaly new to this ....

**Comment by Inversion-NL** [comment]
Great work.
However there are no changes in your commit

**Comment by Drops70** [comment]
This was the only way to open a pull request. Honestly I am a totaly Newbie to github and programming.
I will look deeper into it, but I need help to get the PAN08 device integrated.
Whaterever I can do to get this done I will take care of.

**Comment by Drops70** [comment]
Question:
If I copy the content of a supported device and adjust it like I think it will be OK, would you be able to check wether it is working or needs adjustments. If so, I will spend some time on the weekend to do so.

**Comment by Inversion-NL** [comment]
You should be able to get away with changing the IDs and the capabilities.

**Comment by Drops70** [comment]
Thanks. Just about to learn Java (will take time) and to get used to the development tools from Athom.
Think I will have a first try this weekend.

**Comment by Drops70** [comment]
One additional question. Which files are required? Drivers, app.js, app.json, ..?

**Comment by Drops70** [comment]
Hi, as it is merged now, how is the further process of testing? Will there be a new "beta" release so I can test the function of the PAN08?.
Sorry to ask, but I am still new to this......

**Comment by Inversion-NL** [comment]
There weren't any changes in the commit so nothing has changed.

**Comment by Drops70** [comment]
Sorry, but I dont understand.
Though this is what you needed ....

![pan08](https://user-images.githubusercontent.com/33936869/34567155-04c9f27e-f159-11e7-83d9-1bf6a317344f.JPG)

**Comment by Drops70** [comment]
Hi, 
sorry don't want to bother you, but can you please reply as I have no clue how to proceed at the moment.
I realy need to get this device supported as I have to run my old controller only to get my blinds moving.

Many thanks!
Oliver

**Comment by Inversion-NL** [comment]
The only change in this commit is one empty line.

![screenshot_20180108-192622](https://user-images.githubusercontent.com/15921016/34685831-ebbd0f9c-f4a9-11e7-84ad-2f96f064e145.png)

**Comment by Drops70** [comment]
Thanks for your Feedback.
You are looking at my first "commit" I had no clue what to do.
Please have a look one line after with the "Update PAN08" file.....
This Looks like this (and more):

![commit_pan08](https://user-images.githubusercontent.com/33936869/34711119-03cc0446-f516-11e7-9930-c6039257e00e.JPG)

**Comment by Inversion-NL** [comment]
I'm sorry, I did not know.
Weird that GitHub doesn't show this at the pull request.

**Comment by Inversion-NL** [comment]
Could you please up the version number in app.json and update the readme?
You can add yourself as a developer, if you'd like?

**Comment by Drops70** [comment]
Sure, will do my best, but can take some time unti weekend.
Me a developer? Funny thing, but I might add myself as I did at least some work ... :-)

**Comment by Drops70** [comment]
Did the job - at least hope so ...

**Comment by Inversion-NL** [comment]
Yes, great work.
Did you run and test with this code?

**Comment by Drops70** [comment]
Good morning. No I didn't do any test with the code. I would have done so knowing how to do it.
I know there is a way to do it with Homey , but I didn't look into this so far.

**Comment by Inversion-NL** [comment]
Could you please test it?
It's in the developer documents on the Athom website

**Comment by Drops70** [comment]
Yes I will test it. 
One question. Do I have to test my single code or is there already a "beat" version containing the PAN08 code. If so, which file do I have to download?

**Comment by Drops70** [comment]
Hi,
I get closer. I've copied the driver from Github and installed it yesterday. Today I will try to include the PAN08 Controller.
As all other controllers have an own folder, could you please also open a folder for the PAN08 driver and maybe also copy the asset-folder from the PAN-06 into it (to use the same Image files).

**Comment by Drops70** [comment]
Tested - not working :-(.
Will try to find the mistake ....

**Comment by Drops70** [comment]
Hi, I have tested the driver by creating an own little app for Homey.
It is just a basic driver not supporting the whole features of the PAN08, but it works now since a few weeks :-). I will create a new pull request.

**Comment by mhschaap** [comment]
Hi!
Thanks for your efforts! However, it does not work for me so far. I cannot add the PAN08 shutter controller, I get it added as "simple Z-wave device", which does not give me the desired functionality. Please see screenshot. Any hints? Could I submit a logfile or other details? Thanks!
![PAN08 - 1](https://user-images.githubusercontent.com/50181427/57035361-195aa600-6c52-11e9-9271-bbe9d8a97bb4.jpg)

**Comment by caseda** [comment]
@mhschaap please share the ID's of the device you included.
you can find the ID's in the "simple" device's device settings, under "node information".
Then i can add them into the app.

**Comment by mhschaap** [comment]
@caseda, Thanks for your reply, that would be great! I bought 4 devices, but have installed just one yet, as it did not work so far.  I use a different language, so I have added a screenshot which should include all ID's. Please let me know if you need more, or if I should run a test or create a logfile (although I have no experience with this). 
![PAN08 - 1 (1)](https://user-images.githubusercontent.com/50181427/57184039-9b96d480-6eb5-11e9-9444-d9b2287b0fa3.jpg)

**Comment by mhschaap** [comment]
> @mhschaap please share the ID's of the device you included.
> you can find the ID's in the "simple" device's device settings, under "node information".
> Then i can add them into the app.

@caseda thanks again for your reply! Do you require more info, then what I have added last weekend? Could I do a test-run. Please let me know. Many thanks!!!

**Comment by caseda** [comment]
The id's are included in the app, the PR is awaiting acceptance of the developer, and then can be submitted into the appstore (beta channel).

But feel free to download the code and install the app (v0.1.1) via CLI

**Comment by mhschaap** [comment]
it seems like Product ID is 21 for my device, and the code says "6". I am not a developer, but if I could simply edit the code on my Homey with Vi over ssh/telnet or such, I could give it a go? Please let me know. I have no experience with direct access to Homey. 
![image](https://user-images.githubusercontent.com/50181427/57284706-04e33700-70b2-11e9-941a-fabff966630a.png)

**Comment by mhschaap** [comment]
> But feel free to download the code and install the app (v0.1.1) via CLI
Thanks again!! I will not be home today, but I will give it a try (have not done this before)

**Comment by mhschaap** [comment]
> The id's are included in the app, the PR is awaiting acceptance of the developer, and then can be submitted into the appstore (beta channel).
> 
> But feel free to download the code and install the app (v0.1.1) via CLI

the "issues" has been resolved, but the updated code still lacks ID "21", while it was in your change-request. But I might not understand the github procedure

**Comment by caseda** [comment]
you do need to install the beta app (which isn't in the app store yet) or the code via CLI, anything before v0.1.0 will not have the ID

**Comment by mhschaap** [comment]
Thanks for your efforts, I appreciate. 👍 

I would have liked to have it working by now. My apparently supported devices can’t be used. But I have to deal with that

**Comment by caseda** [comment]
Just wait only a few more days, don't think it will take long for the beta app be in the app store.
I know it can be frustrating.

**Comment by mhschaap** [comment]
Just wanted to let you know that I have just downloaded via CLI version 0.1.1 and could successfully include my PAN08 device. I have not really used it yet, as I have very little time at this moment. Just wanted to say thanks!!

Few things I noticed:
- in an "if" condition I can choose "dim level has changed", literally "Dim-niveau is veranderd"
- in the Devices section (apparaten) it also shows the dim-level
I guess this is just a textual thing. Could post screenshots if you would like. 

I will keep you posted after proper testing. Thanks again

**Comment by mhschaap** [comment]
![Screenshot 2019-05-10 at 20 54 37](https://user-images.githubusercontent.com/50181427/57550305-4a2f8f00-7366-11e9-8030-b92c2268b83b.png)
I think there is a bug:
- if "state == up", then I can give the "up command"
- it should be if "state != up", then I should be able to give the "up command" 

Even when wrong wired, or such (which is not the case), this logic is reversed imho. I looked in the code of this App, but this logic is programmed at another level?

**Comment by caseda** [comment]
It shouldn't be called dim level with that class, that's an athom bug.
Also yes, all those cards are created by athom's core functionality, don't have any control over that.

**Comment by mhschaap** [comment]
I have a question about the intention of the "state up/down" booleans:

when sunscreen is 50% open (and shown as 50% open in the PAN08 device section):
- boolean up should be false and boolean down should be false as well right?
- we mean the full 0% or the full 100% and nothing in between?

Either way, without changing the position, when I run a test-flow, it gives different results for this query. That is anyhow strange. Any comments on that? 

![image](https://user-images.githubusercontent.com/50181427/57686200-75053600-7639-11e9-9078-7abbc0cc5847.png)
![image](https://user-images.githubusercontent.com/50181427/57686832-974b8380-763a-11e9-9306-141eb1a1965d.png)

In order to check against automatic control overriding manually opened sunscreens, it would be great to have a condition: "if sunscreen open > 5%" or such. If this condition is the case we know:
1. the sunscreen is down already, but manually set at whatever value; so we will not interfere.
2. we can check in case of wind or rain if the sunscreen is (partly) open, so that we can close it. But by this 5% check we avoid sending repeatedly up commands while it is up already

Thanks for sharing your thougths as well!

**Comment by caseda** [comment]
You can do that with logic cards, if more then (tag percentage open): 5%
Further I have no clue how the rest is handled, I didn't implement the device, and never worked with roller shutter before with zwave.

 I guess I should have deleted the capability anyway, and only leave the slider.

**Comment by mhschaap** [comment]
> You can do that with logic cards, if more then (tag percentage open): 5%
> Further I have no clue how the rest is handled, I didn't implement the device, and never worked with roller shutter before with zwave.
> 
> I guess I should have deleted the capability anyway, and only leave the slider.

YESSS you are right, I did not recognize that! It is not available directly from the PAN08, but as a regular "logic card", perfect! This also solves the boolean test issues, I guess this is the more reliable approach!

**Comment by mhschaap** [comment]
can you also explain the -100% <-> + 100% slider? what is considered -100% and what is +100%? 
normally I would expect: 0% is up, 100% is down, or vice-versa.
![image](https://user-images.githubusercontent.com/50181427/57690923-1e9cf500-7643-11e9-8f81-446949a8a571.png)

Thanks again!!

**Comment by caseda** [comment]
It is relative, change from where it is now,
is it at 50% change it -10% makes it 40% as new value
Is it at 20% change it +30% makes the new value 50%

**Comment by picaro1** [comment]
I'm new here.
Tried adding PAN08 to Homey. Version 0.0.30.
Got a generic Z-Wave device with only an 'power'-button. Not of any use.
Then de-installed the device.
Used the beta-version of the app and tried to add it again.
Now I've got the error message stating that the device is already added, however it does not appear in my list of devices!

**Comment by caseda** [comment]
@picaro1 please try resetting your device to factory default, either by following the device manual, or from the developer tools -> z-wave -> remove device

**Comment by picaro1** [comment]
Thanks @caseda !
Tried the factory default, that didn't work. However it worked through 'developer tools'.
Do you now how to calibrate the dim value?

**Comment by caseda** [comment]
i do not have the device, so no

**Comment by mhschaap** [comment]
Calibration is only needed by the device itself, not through Homey. It is described in the manual that comes with the product (press the button in certain way)

**Comment by thestormhunter** [comment]
Hi everyone,

Does anyone know when the PAN-08 is included to Homey? Mine also is added as "simple Z-wave device". Or can someone please help to get it fixed? 

Thanks for your support!

**Comment by mhschaap** [comment]
> Hi everyone,
> 
> Does anyone know when the PAN-08 is included to Homey? Mine also is added as "simple Z-wave device". Or can someone please help to get it fixed?
> 
> Thanks for your support!

Use the Beta version, there it’s included

**Comment by caseda** [comment]
with the new app store there isn't really a beta version anymore, but a [test version](https://homey.app/nl-nl/app/com.philio/Philio/test/) <= click for the link

**Comment by thestormhunter** [comment]
Thanks for the fast response. That one i had allready installed, i can select the PAN08 but it doesn't reconise the PAN08 that i have.

**Comment by mhschaap** [comment]
> Thanks for the fast response. That one i had allready installed, i can select the PAN08 but it doesn't reconise the PAN08 that i have.
![0CAC0C7B-628B-4488-B02A-B26E8D7EF826](https://user-images.githubusercontent.com/50181427/74091595-83458d00-4ab9-11ea-914d-6da38f1fb7f1.jpeg)

Please check if you really have v0.1.1 installed, this solved it for me

**Comment by thestormhunter** [comment]
I have removed the app and installed it again. Now it works perfectly. Thanks for your help! Kind regards
