### ISSUE TITLE
Tamper Alarm - PST02-C

### ISSUE THREAD

**Issue by fredrikhanssonsk** [JohanBendz/com.philio#36]
Tamper Alarm is always active and i havent found a way to null it.
Both tamper switches are pressed down.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC11.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC13.

**Comment by Inversion-NL** [comment]
Most likely an problem in Homey https://github.com/athombv/homey/issues/2243 and https://github.com/athombv/homey/issues/1785

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.8-EXP from 08.03.18.

**Comment by Inversion-NL** [comment]
Because it still isn't resolved in Homey: https://github.com/athombv/homey/issues/2267

**Comment by CyberSponk** [comment]
Reported it Today in the linked Issue: **Not** fixed in 1.5.8-exp. Updated ~10 hours ago. WakeUp-Time of Devices 6 hours. Tamper-Alarm is On.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.11-EXP.

**Comment by CyberSponk** [comment]
Changed all Philio to Fibaro > Could not assist here in future.

**Comment by ThomasHoussin** [comment]
I have the same problem (tamper alarm that don't go away) - using latest beta in the application. Is there a way to fix this ?

**Comment by JohanBendz** [comment]
Hi @ThomasHoussin, can you please create a crash report from the app so that I can see what's wrong?

**Comment by ThomasHoussin** [comment]
Done, hope it helps. How can I send you the code ?

**Comment by JohanBendz** [comment]
Hi @ThomasHoussin, can you please try this version and see if the issue is resolved? https://homey.app/a/com.philio/test/
