### ISSUE TITLE
Pan11-3 support as well as Pan11-1

### ISSUE THREAD

**Issue by cscottmcqueen** [JohanBendz/com.philio#45]
Hi,  Would it be possible to include support for all three of the variants as I just bought 2 pan11-3E’s hoping they would be the same?

I believe it is just the interface type and ID that is different:

PAN11-1 ZC08-13020005 
PAN11-2 ZC08-13020006 
PAN11-3 ZC08-13020007

I am not sure about PAN11-2 (I believe it is Product Type ID 1 and the Product ID of 11  ) but the PAN11-3 has the Product Type ID 1 and the Product ID of 48

Thanks Scott

**Comment by caseda** [comment]
nice try, id 11 for `-2` = hexadecimal value, not the used decimal value, but wil add the id's in the SDKv2 rewrite

**Comment by JohanBendz** [comment]
If this is still an issue, please create a new issue.
