### ISSUE TITLE
Homey 2.0 can't insta

### ISSUE THREAD

**Issue by ff20000** [JohanBendz/com.philio#46]
I want to install this app. But it won't let me.
I already reinstalled homey but this did not worked.

**Comment by ff20000** [comment]
this is what it give back.

[ { "keyword": "type", "dataPath":
". ow.triggers[0].tokens[0].example", "schemaPath":
"#/de nitions/i18nObject/oneOf/0/type", "params": { "type":
"string" }, "message": "should be string" }, { "keyword": "type",
"dataPath": ". ow.triggers[0].tokens[0].example['en']",
"schemaPath":
"#/de nitions/i18nObject/oneOf/1/patternProperties/%5E.*%24/type",
"params": { "type": "string" }, "message": "should be string" }, {
"keyword": "oneOf", "dataPath":
". ow.triggers[0].tokens[0].example", "schemaPath":
"#/de nitions/i18nObject/oneOf", "params": {
"passingSchemas": null }, "message": "should match exactly
one schema in oneOf" }, { "keyword": "type", "dataPath":
". ow.triggers[0].tokens[0].example", "schemaPath":
"#/properties/tokens/items/properties/example/oneOf/1/type",
"params": { "type": "number" }, "message": "should be
number" }, { "keyword": "type", "dataPath":
". ow.triggers[0].tokens[0].example", "schemaPath":
"#/properties/tokens/items/properties/example/oneOf/2/type",
"params": { "type": "boolean" }, "message": "should be
boolean" }, { "keyword": "oneOf", "dataPath":
". ow.triggers[0].tokens[0].example", "schemaPath":
"#/properties/tokens/items/properties/example/oneOf",
"params": { "passingSchemas": null }, "message": "should
match exactly one schema in oneOf" } ]: [object Object]

**Comment by caseda** [comment]
now writing an PR for this app fixing this issue, please stand by 😄

**Comment by JohanBendz** [comment]
Fixed in test version / v0.1.1
