### ISSUE TITLE
PAN11-1E IDed as Generic Device

### ISSUE THREAD

**Issue by asteman** [JohanBendz/com.philio#49]
Hi, 
I have a PAN11-1E that is only IDed as a generic device after inclusion. Tried several times far and close to Homey. Same result.
Manufacture ID: 316
Product Type ID: 1
Product ID: 48
Firmware version: 304

Homey 1.5.13

Am I doing it wrong or is there something else wrong?

**Comment by stefansandor** [comment]
I just tried with three different PAN11-1E and they are included as smart plugs, but are unable to report energy and other information to Homey. They are not smart and can only be used for on-off as a generic device (even though they are identified correctly). The info about voltage, etc is only presented as "-" (i.e. no reading).
