### ISSUE TITLE
PSE02-1B siren support

### ISSUE THREAD

**Issue by asteman** [JohanBendz/com.philio#50]
Hi,
Moving from Vera to Homey I just realized there is no support for the PSE02-1B siren. I'm using it as in indoor siren and door chime. Is it possible to add support for it? Are there any information I can provide to help?
\\ Andreas

**Comment by JohanBendz** [comment]
Hi @asteman, please provide device information for me to be able to add it.
Device model/name:
Manufacture ID:
Product Type ID:
Product ID:

**Comment by asteman** [comment]
Hi,

Device model/name: PH-PSE02-1B.EU
Manufacture ID: 316
Product Type ID: 4
Product ID: 10

**Comment by JohanBendz** [comment]
Added to Test version 0.1.3, please try and give feedback
