### ISSUE TITLE
tamper alarm always on pat02-1b

### ISSUE THREAD

**Issue by grolsch1986** [JohanBendz/com.philio#51]
the temper alarm is always on whats the problem off this

**Comment by TechnoX** [comment]
I see the same problem on my PAT02-1B. Using Homey (model called early 2019 and version 2.0.2) with the homey app 2.0.6.250

**Comment by JohanBendz** [comment]
Hi @grolsch1986 and @TechnoX 
Can any of you guys please restart the app, make sure you notice the issue described above and send me a crash report from the app?

**Comment by TechnoX** [comment]
Hi Johan!

Finally updates here! Thanks!


How do I generate such report? The app has never crasched. Under settings and general I can create a diagnostics report. I got this ID:  919532A0D2

The problem persist though. See image below:

![Screenshot_20200731-145153](https://user-images.githubusercontent.com/1463156/89036694-6e95d380-d33d-11ea-9ccc-06402b20fbda.jpg)

**Comment by JohanBendz** [comment]
Hi @TechnoX, can you please try the test version here and see if your issue persists: https://homey.app/a/com.philio/test/
