### ISSUE TITLE
Is the Philio compatible with V2 now?

### ISSUE THREAD

**Issue by SanderVlotman** [JohanBendz/com.philio#54]
Hi I'm using several Philio Slim Multi-Sensor PSM02 4:1 on my Homey and can't find out if it the app is compatibel with V2 now and if this device is working. On the Athom Community Forum someone mentioned tha app does not install.

**Comment by mardda** [comment]
Wonder the same, have issues with motiondetection mainly. Activate but no deactivation.
App installs and seems tog work for the main part in my setup. I och have one Philio Slim Multi-Sensor PSM02 4:1.

**Comment by caseda** [comment]
the app has been v2 compatible ever since the last update, just finishing up the SDKv2 re-write but it is not mandatory, it works just fine

**Comment by JohanBendz** [comment]
Fixed in v.0.1.1
